### ISSUE TITLE
Installation fails if you're using docker-edge

### ISSUE THREAD

**Issue by luisdavim** [habitat-sh/homebrew-habitat#11]
If you have Docker edge installed, this package will still try to install docker as a dependency and fail because do docker is already installed.

**Comment by christophermaier** [comment]
Is this happening when you install habitat from Homebrew, or once you try to use habitat after it's been installed? The Homebrew formula itself shouldn't be pulling in any kind of Docker.

**Comment by luisdavim** [comment]
hi, this is happening when installing:
```
Re-installing hab
==> Satisfying dependencies
==> Installing Cask dependencies: docker
==> Satisfying dependencies
==> Downloading https://download.docker.com/mac/stable/26399/Docker.dmg
######################################################################## 100.0%
==> Verifying checksum for Cask docker
==> Installing Cask docker
==> Purging files for version 18.06.0-ce-mac70,26399 of Cask docker
Error: It seems there is already an App at '/Applications/Docker.app'.
```

it tries to get Docker because it's a dependency, I don't have the docker cask installed because I use the docker-edge cask but I guess the same happens if someone manually installs docker and then tries to install habitat.

**Comment by christophermaier** [comment]
@luisdavim Are you using this repository as a tap? The formula here doesn't actually have Docker as a dependency.

**Comment by luisdavim** [comment]
Oh, sorry. Now I am. I was using the cask. With this tap I don't have the problem anymore. Thanks for your help.
